version: "3"
services: 
    postgres:
        image: postgres:11.12
        container_name: postgres
        ports: 
            - 5555:5432
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
        tty: true
        restart: always
        user: root
        volumes:
        - ./init:/docker-entrypoint-initdb.d
        - /etc/localtime:/etc/localtime:ro
    pgweb:
        image: sosedoff/pgweb:0.11.7
        container_name: pgweb
        ports: 
            - "8081:8081"
        environment:
            - DATABASE_URL=postgres://root:password@postgres:5432/root?sslmode=disable
        links: 
            - postgres:postgres
        restart: always
        depends_on:
            - postgres
